import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({
    baseUrl: "/api/v1",
  }),
  tagTypes: [
    "Product",
    "Category",
    "Brand",
    "Unit",
    "Variant",
    "Warehouse",
    "TaxRate",
    "Customer",
    "CustomerGroup",
    "Supplier",
    "Biller",
    "Sale",
    "Purchase",
    "Return",
    "Transfer",
    "Quotation",
    "Expense",
    "ExpenseCategory",
    "Payment",
    "Adjustment",
    "StockCount",
    "Delivery",
    "GiftCard",
    "Promo",
    "Printer",
    "Currency",
    "PriceGroup",
    "User",
    "PermissionGroup",
    "Dashboard",
    "Report",
    "Settings",
  ],
  endpoints: () => ({}),
});
